### ISSUE TITLE
What License is this code shared under?

### ISSUE THREAD

**Issue by nickfraser** [fastmachinelearning/pytorch-training#3]
I'm working on a project which uses a modified version of the `Data_loader.py` file contained in this repo. What license applies to this file? Are there any issues in me using a modified version of this source (with attribution, of course) in my project? This project I'm planning to release under the Apache 2.0 license.

**Comment by zhenbinwu** [comment]
Thank you for reminding us. This repo is now under the Apache 2.0 license.
